---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "go-log.fullname" . }}
  namespace: {{ default "eml" .Values.namespace  }}
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 100Mi
    min:
      storage: 20Mi



---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "go-log.fullname" . }}
  namespace: {{ default "eml" .Values.namespace  }}
spec:
  hard:
    requests.storage: 100Mi
    value.storageclass.storage.k8s.io/requests.storage: 50Mi



---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "go-log.fullname" . }}
  namespace: {{ default "eml" .Values.namespace  }}
spec:
  storageClassName: v1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi


---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "go-log.fullname" . }}
  namespace: {{ default "eml" .Values.namespace  }}
  labels:
    type: local
spec:
  storageClassName: v1
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 50Mi
  limit:
    storage: 50Mi     
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ default "/home/app_data" .Values.go_pv.path  }}

